#server propeties
server:
  port: 8888


#app-name
spring:
  application:
    name: CONFIG-SERVER

#config server properties
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/swamymasna/sbms-kes-project-repo.git
          uri: https://github.com/swamymasna/sbms-kes-project-yml-repo.git
          username: swamymasna@gmail.com
          password: Swamy@156
          clone-on-start: true
          default-label: master
        bootstrap: true  
        
#eureka properties
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${random.value}    
    
#actuator properties    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    
    
    